Some weights of LlamaForSequenceClassification were not initialized from the model checkpoint at meta-llama/Llama-3.2-1B-Instruct and are newly initialized: ['score.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/yutong-8gpus-training/code/Users/yutong.jiang2/Pretrain_LLM/PPO/PPO.py", line 31, in <module>
    reward_model = AutoModelForSequenceClassification.from_pretrained(config.reward_model_name, num_labels = 1)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
    resolved_config_file = cached_file(
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1240, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1303, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1751, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1673, in get_hf_file_metadata
    r = _request_wrapper(
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 376, in _request_wrapper
    response = _request_wrapper(
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 399, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/requests/adapters.py", line 589, in send
    resp = conn.urlopen(
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/site-packages/urllib3/connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/home/azureuser/.pyenv/versions/3.10.12/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt